export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const SET_USER_NAME = 'SET_USER_NAME';
export const GET_COLLEAGUE_NAME = 'GET_COLLEAGUE_NAME';
export const GET_COLLEAGUE_JOB_TITLE = 'GET_COLLEAGUE_JOB_TITLE';
export const GET_COLLEAGUE_CONTACT = 'GET_COLLEAGUE_CONTACT';
